package com.example.pet_tracker.model;

import javax.persistence.*;
/**
 * Abstract base class representing a generic Pet entity.
 * This class is part of a single-table inheritance hierarchy.
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE) // Use a single database table for all subclasses
@DiscriminatorColumn(name = "pet_type") // Column used to differentiate between subclass types (e.g., DOG, CAT)
public abstract class Pet {
    
    // Primary key for the Pet entity, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String trackerType;

    @Column(nullable = false)
    private Integer ownerId;

    @Column(nullable = false)
    private Boolean inZone;

    public Pet() {}
    
    /**
     * Parameterized constructor to initialize the Pet with tracker type, owner ID, and zone status.
     *
     * @param trackerType the type of tracking device
     * @param ownerId     the owner's ID
     * @param inZone      zone status (true if in zone, false otherwise)
     */
    public Pet(String trackerType, Integer ownerId, Boolean inZone) {
        this.trackerType = trackerType;
        this.ownerId = ownerId;
        this.inZone = inZone;
    }

    // Getters and Setters
    public Long getId() { return id; }

    public String getTrackerType() { return trackerType; }

    public void setTrackerType(String trackerType) { this.trackerType = trackerType; }

    public Integer getOwnerId() { return ownerId; }

    public void setOwnerId(Integer ownerId) { this.ownerId = ownerId; }

    public Boolean getInZone() { return inZone; }

    public void setInZone(Boolean inZone) { this.inZone = inZone; }
}
